# Generated by Django 3.1.2 on 2021-02-03 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0009_post_commentcount'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_details',
            name='about',
            field=models.TextField(null=True),
        ),
    ]
